### ISSUE TITLE
global .helmignore

### ISSUE THREAD

**Issue by klml** [it-at-m/helm-charts#23]
global .helmignore

**Comment by eidottermihi** [comment]
I'm not an expert on this and didnt find any "best practice", but I think there's a need to configure this on a per-chart basis, because helm is packaging one chart at-a-time and I don't think it is considering a `.helmignore` outside the chart directory.

Other "big" chart repositories (like [bitnami](https://github.com/bitnami/charts/tree/main/bitnami)) also don't have a global .helmignore.

@klml Do you have more insight on this? If not, I'm pending towards closing the issue.
